"""modulo criterios

Revision ID: 05c74fcbd6f3
Revises: d6adcbabf975
Create Date: 2026-07-14 09:18:25.104191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c74fcbd6f3'
down_revision: Union[str, Sequence[str], None] = 'd6adcbabf975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_criterio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('clasificacion', 'asignacion_revisor', name='tipo_criterio'), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=False),
    sa.Column('subido_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'version', name='uq_documento_criterio_tipo_version')
    )
    op.create_table('pines_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sa.String(length=200), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pines_admin')
    op.drop_table('documentos_criterio')
    # ### end Alembic commands ###
