"""modulo clasificacion de ideas

Revision ID: 069735b9bdb9
Revises: dce7a6c777ac
Create Date: 2026-07-14 13:46:31.734749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069735b9bdb9'
down_revision: Union[str, Sequence[str], None] = 'dce7a6c777ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente_clasificacion', 'clasificada', name='estado_clasificacion'), nullable=False),
    sa.Column('clasificacion', sa.Enum('innovacion', 'transformacion_digital', name='tipo_cab_clasificacion'), nullable=True),
    sa.Column('clasificado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_clasificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['clasificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clasificacion_ideas')
    # ### end Alembic commands ###
