"""analisis de riesgo automatico y evaluacion rice

Revision ID: 8601a283f177
Revises: de88ae0d351e
Create Date: 2026-07-20 16:29:12.735873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8601a283f177'
down_revision: Union[str, Sequence[str], None] = 'de88ae0d351e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_riesgo_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('probabilidad', sa.Integer(), nullable=False),
    sa.Column('impacto', sa.Integer(), nullable=False),
    sa.Column('nivel_riesgo', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('bajo', 'moderado', 'medio_alto', 'alto', 'critico', name='categoria_riesgo'), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id')
    )
    op.create_table('rice_evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comite_idea_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('lider_funcional', sa.String(length=200), nullable=False),
    sa.Column('paises', sa.Integer(), nullable=False),
    sa.Column('presupuesto_rango', sa.Enum('cero', 'hasta_10000', 'hasta_20000', 'hasta_30000', 'mas_30000', name='presupuesto_rango'), nullable=False),
    sa.Column('impacta_plan_estrategico', sa.Boolean(), nullable=False),
    sa.Column('alcance_departamentos', sa.Integer(), nullable=False),
    sa.Column('impacto', sa.Enum('muy_bajo', 'medio', 'alto', 'muy_alto', name='rice_impacto'), nullable=False),
    sa.Column('confianza', sa.Enum('muy_bajo', 'medio', 'alto', 'muy_alto', name='rice_confianza'), nullable=False),
    sa.Column('esfuerzo', sa.Enum('corto_plazo', 'medio_plazo', 'largo_plazo', name='rice_esfuerzo'), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_rice'), nullable=False),
    sa.Column('completado_por_id', sa.Integer(), nullable=False),
    sa.Column('completado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['comite_idea_id'], ['comite_ideas.id'], ),
    sa.ForeignKeyConstraint(['completado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comite_idea_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rice_evaluaciones')
    op.drop_table('analisis_riesgo_ideas')
    # ### end Alembic commands ###
