"""bloqueo y limite diario de pin admin

Revision ID: 9f4557192f21
Revises: 05c74fcbd6f3
Create Date: 2026-07-14 10:36:51.599497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4557192f21'
down_revision: Union[str, Sequence[str], None] = '05c74fcbd6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' es necesario porque ya existen filas en pines_admin
    # (usuarios que definieron su PIN antes de esta migración); se quita
    # después para que el esquema quede igual al definido en el modelo
    # (default=0 solo a nivel de aplicación, no a nivel de columna).
    op.add_column('pines_admin', sa.Column('intentos_fallidos', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pines_admin', sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pines_admin', sa.Column('cambios_hoy', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pines_admin', sa.Column('fecha_ultimo_cambio', sa.Date(), nullable=True))
    op.alter_column('pines_admin', 'intentos_fallidos', server_default=None)
    op.alter_column('pines_admin', 'cambios_hoy', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pines_admin', 'fecha_ultimo_cambio')
    op.drop_column('pines_admin', 'cambios_hoy')
    op.drop_column('pines_admin', 'bloqueado_hasta')
    op.drop_column('pines_admin', 'intentos_fallidos')
    # ### end Alembic commands ###
