"""modulo revision de ideas

Revision ID: dce7a6c777ac
Revises: c8d99efd0daf
Create Date: 2026-07-14 13:32:01.213570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce7a6c777ac'
down_revision: Union[str, Sequence[str], None] = 'c8d99efd0daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente_asignacion', 'pendiente_revision', 'aprobada', 'cambios_solicitados', name='estado_revision'), nullable=False),
    sa.Column('retroalimentacion', sa.Text(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_ideas')
    # ### end Alembic commands ###
