"""asignacion automatica de revisor por ia

Revision ID: de88ae0d351e
Revises: f959a119c96d
Create Date: 2026-07-20 09:54:53.939324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de88ae0d351e'
down_revision: Union[str, Sequence[str], None] = 'f959a119c96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('sugerencia_revisor_autor', sa.String(length=300), nullable=True))
    op.add_column('ideas', sa.Column('motivo_sugerencia_revisor_autor', sa.Text(), nullable=True))
    op.add_column('revision_ideas', sa.Column('departamento_sugerido_ia_id', sa.Integer(), nullable=True))
    op.add_column('revision_ideas', sa.Column('justificacion_ia', sa.Text(), nullable=True))
    op.add_column('revision_ideas', sa.Column('acepto_sugerencia_autor', sa.Boolean(), nullable=True))
    op.create_foreign_key(
        'fk_revision_ideas_departamento_sugerido_ia_id',
        'revision_ideas', 'departamentos', ['departamento_sugerido_ia_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_revision_ideas_departamento_sugerido_ia_id', 'revision_ideas', type_='foreignkey')
    op.drop_column('revision_ideas', 'acepto_sugerencia_autor')
    op.drop_column('revision_ideas', 'justificacion_ia')
    op.drop_column('revision_ideas', 'departamento_sugerido_ia_id')
    op.drop_column('ideas', 'motivo_sugerencia_revisor_autor')
    op.drop_column('ideas', 'sugerencia_revisor_autor')
    # ### end Alembic commands ###
