"""modulo comites de cab

Revision ID: e47dea031bf6
Revises: 069735b9bdb9
Create Date: 2026-07-14 14:30:07.188381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47dea031bf6'
down_revision: Union[str, Sequence[str], None] = '069735b9bdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comite_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cab', sa.Enum('innovacion', 'transformacion_digital', name='tipo_cab_comite'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_comite'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('aprobada_o_rechazada_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['aprobada_o_rechazada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comite_ideas')
    # ### end Alembic commands ###
